# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

author:
  name: Gabriel Carneiro
  email: gabriel.chaves.carneiro@gmail.com
  phone: "+55 31 98878-3072"

title: Gabriel Carneiro
email: gabriel.chaves.carneiro@gmail.com
description: >-
  I completed my Computer Science degree at UFSJ and I'm currently pursuing my master's.
  Outside of my academic journey, I'm deeply involved in open-source projects, particularly those centered on Linux.
  I'm also a proud cat owner.

baseurl: ""
url: "https://therealcarneiro.github.io"
github_username: theRealCarneiro

# Build settings

plugins:
  # - jekyll-remote-theme
  - jekyll-feed
  - jekyll-scholar
  - jekyll-seo-tag

header_pages:
  - pages/index.html
  - pages/about.html
  - pages/publications.html
  - pages/education.html
  - pages/resume.html
  - pages/repos.html

collections_dir: collections

# remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/theRealCarneiro" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/therealcarneiro/" }
    - { platform: lattes, user_url: "http://lattes.cnpq.br/2090658657681256" }

collections:
  repos:
    output: false
    sort_by: year
    permalink: /:collection/:name

  education:
    output: false
    sort_by: start_year
    permalink: /:collection/:name

scholar:
  # style: assets/csl/acm.csl #apa  #chicago-fullnote-bibliography #apa
  style: _includes/csl/acm.csl

  sort_by: year, month
  order: descending # ascending
  group_by: year
  group_order: descending # ascending

  source: collections/_bib
  repository: papers
  bibliography: "*.bib"
  bibliography_template: bib

  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
